### ISSUE TITLE
As a user, I want to like and comment on podcasts to share my thoughts and engage with the community.

### ISSUE THREAD

**Issue by sFranchetto** [awaazo/awaazo#10]
**Acceptance Criteria:**  
- [x] "Like" and "Comment" options are visible for every podcast episode.
- [x] Clicking "Like" highlights the icon and updates the count.
- [x] Comments can be added using a textbox and are displayed once posted.
- [x] Other users can view, like, or reply to these comments.

**Demo Steps:**  
1. Navigate to a podcast episode.
2. Click "Like".
3. Enter a comment and post it.
4. View the posted comment in the episode's comment section.

**Potential Risks:**  
1. Privacy concerns related to user engagements.
2. Delays in updating engagements due to server issues.
3. Inadequate moderation of inappropriate comments.
4. Accidental public display of private engagements.

**Comment by mathieutrudeau** [comment]
The backend endpoints are completed and available on the branch

**Comment by Ahed752** [comment]
https://github.com/awaazo/awaazo/assets/77853391/0168d90d-4ed7-46c1-8ba6-fb7a145e2888

**Comment by jonathan-githubofficial** [comment]
missing tests
