### ISSUE TITLE
As a user, I want to easily upload and add episodes to a podcast, to ensure my content reaches my listeners.

### ISSUE THREAD

**Issue by jonathan-githubofficial** [awaazo/awaazo#110]
## Acceptance Criteria:  
- [x] From "My Podcasts", users can select a podcast and add a new episode.
- [x] Upon selecting to add a new episode, users can upload an audio file.
- [x] The platform accepts common audio formats, auto-converting uploads to optimal MP3 with VBR.
- [x] Users can input episode details such as cover art, name, description, and any other necessary metadata.
- [x] Once uploaded, episodes are immediately available for streaming.
- [x] User is able to attached an episode to a podcast.

## Demo Steps:  
1. Navigate to "My Podcasts".
2. Choose a podcast and click "Add New Episode".
3. Upload an audio file and set its details.
4. Confirm episode's availability on the platform.
5. Add episode to a podcast.

## Potential Risks:  
1. Potential delays in episode availability due to server congestion.
2. Oversized uploads may lead to system performance issues.

**Comment by jonathan-githubofficial** [comment]
**Side Comment:**
Upon uploading the audio file, the system will utilize ffmpeg to convert it to an MP3 format with VBR. This ensures that the audio retains a good quality while being optimal for streaming. Once processed, the episode will be stored in the database, ready for listeners to stream.

**Comment by jonathan-githubofficial** [comment]
dependent on issue #18

**Comment by mathieutrudeau** [comment]
[THIS ISSUE](https://github.com/awaazo/awaazo/issues/139) has completely refactored the backend endpoints that are being used in this issue.

**Comment by usamasaleem1** [comment]
Usama[frontend]#1: Created frontend design for uploading a podcast episode

https://github.com/awaazo/awaazo/assets/50121574/816543c0-e4c2-4548-978f-1f8a4516509f

**Comment by sFranchetto** [comment]
https://github.com/awaazo/awaazo/assets/31280516/d9ae3d20-44af-483f-86c9-906e1d695b2f


Commit where this was done: https://github.com/awaazo/awaazo/commit/8a95f14ee049c767cf9988d52f74ec4867537b73

**Comment by sFranchetto** [comment]
**Part 2**

https://github.com/awaazo/awaazo/assets/31280516/5efde82e-6951-4707-ac83-c8b551dd2779


Commit where this was done: https://github.com/awaazo/awaazo/commit/8a95f14ee049c767cf9988d52f74ec4867537b73

**Comment by Radwanbaba13** [comment]
Radwan[frontend]: Functionality of Create Podcast and Upload Episode
https://github.com/awaazo/awaazo/assets/68618601/6b4800c1-05c1-4ecf-a9dd-e445a3db1e6d
