### ISSUE TITLE
As a user, I want to view other user's profile, so that I can view their interests and activity

### ISSUE THREAD

**Issue by sFranchetto** [awaazo/awaazo#112]
## Acceptance Criteria:  
- [x] The profile page of another user should display their podcasts, and general information set by that user.
- [x] The page should not provide any option to edit the profile or follow the user.
- [x] The design of the page should be consistent with the overall platform's aesthetics.
- [x] The content on the page should be properly aligned, displayed and responsive.

## Demo Steps:  
1. Navigate to the profile of a user from the main interface.
2. Verify that the profile page displays the podcasts, and general public information of the respective user.
3. Confirm that there are no options available for editing the profile or following the user.

## Potential Risks:  
- Unauthorized access to edit functionality if not properly restricted.
- Inconsistencies in the design might lead to a poor user experience.

**Comment by mathieutrudeau** [comment]
#143 Adds the backend endpoints needed to retrieve the User Profile information.

**Comment by Radwanbaba13** [comment]
Radwan[frontend]: View other users' profiles


https://github.com/awaazo/awaazo/assets/68618601/c96a6138-cebd-44cf-a48e-d64e49e059f2

**Comment by sFranchetto** [comment]
Search bar only taking one character at a time before I have to re-click the bar

**Comment by sFranchetto** [comment]
https://github.com/awaazo/awaazo/assets/31280516/29422d31-7c33-4086-bc7c-3d41dbd8cdad



Commit where this was done: [Commit](https://github.com/awaazo/awaazo/commit/f5ce0024d1b3fdd79503b78447fe34532addf013)
