### ISSUE TITLE
Subscribe button under My Podcasts container

### ISSUE THREAD

**Issue by sFranchetto** [awaazo/awaazo#113]
**Problem:**
Users currently find it challenging to easily subscribe to their favorite podcasts directly from the "My Podcasts" section. This lack of a prominent subscription option leads to a cumbersome process of finding and subscribing to podcasts they enjoy.

**Solution:**
Introducing a "Subscribe" button directly under the podcast would streamline the subscription process for users. With this feature, users can promptly subscribe to their preferred podcasts without having to navigate to individual podcast pages. This will enhance user engagement and satisfaction by simplifying the podcast subscription experience.

**Alternatives:**
An alternative approach could be to integrate a subscription option within the podcast details section, requiring users to access individual podcast pages to subscribe. However, this approach might add unnecessary steps and reduce user convenience, ultimately impacting user engagement.

**Context:**
Attaching a mockup to illustrate the proposed "Subscribe" button's placement in the "My Podcasts" container for better visualization and understanding. This feature enhancement aligns with our goal of improving user experience and increasing user retention by making podcast subscription more accessible and user-friendly.

**Comment by jonathan-githubofficial** [comment]
duplicate issue
