### ISSUE TITLE
As a user, I want to access My Podcasts from the navbar, for easier navigation.

### ISSUE THREAD

**Issue by sFranchetto** [awaazo/awaazo#114]
## Acceptance Criteria:  
- [x] The "My Podcasts" page is accessible from the navbar, providing a direct link for easy navigation.
- [x] The page should display all the podcasts uploaded by the user.
- [x] Users should be able to edit podcast cover photos and descriptions directly from this page.
- [x] The design of the page should be user-friendly, intuitive, and consistent with the overall platform's aesthetics.

## Demo Steps:  
1. Ensure a user is logged in.
2. Navigate to the "My Podcasts" page from the navbar.
3. Ensure that all the user's uploaded podcasts are displayed on the page.
4. Try editing the cover photo and description of a podcast and confirm that the changes are saved.

## Potential Risks:  
- Complex implementation may lead to technical glitches and performance issues.
- Inadequate security measures may result in unauthorized access to user data and content.
- Poorly designed user interface may lead to confusion and a steep learning curve for users unfamiliar with the admin dashboard concept.

**Comment by usamasaleem1** [comment]
Usama[frontend]#1:Frontend Design Explanation
https://github.com/awaazo/awaazo/assets/50121574/ae8b97be-4532-4c31-87d0-fd1fb0b86b59
