### ISSUE TITLE
Fix the layout and respostivity of the player page 

### ISSUE THREAD

**Issue by jonathan-githubofficial** [awaazo/awaazo#117]
The player page has misaligned elements and doesn't adapt well to various screen sizes, causing overlapping elements, distorted visuals, and reduced functionality on mobile devices. A redesign and thorough testing on multiple devices should be done.

**Comment by usamasaleem1** [comment]
Usama[frontend]#1: Now playing bar is now responsive

https://github.com/awaazo/awaazo/assets/50121574/97412b2a-d298-46f6-86ff-58add21016b2
