### ISSUE TITLE
As a user, I want to be able to sign up with a unique username and email, so that I can have a personalized account and login with either my username or email.

### ISSUE THREAD

**Issue by jonathan-githubofficial** [awaazo/awaazo#119]
## Acceptance Criteria:  
- [x] User must be able to input a username on the sign-up page.
- [x] User must be able to input an email on the sign-up page.
- [x] Usernames must be unique across all accounts.
- [x] Emails must be unique across all accounts.
- [x] A user must be able to login with either their username or email.

## Demo Steps:  
1. Show the updated sign-up page with the new username field.
2. Sign up a new user with a unique username and email.
3. Attempt to sign up another user with the same username or email to show the error message.
4. Log out and log back in using the new account's username.
5. Log out and log back in using the new account's email.

## Potential Risks:  
- There might be complications with the login system when integrating the option to login with either username or email.
- Ensuring the uniqueness of usernames and emails might require changes to the database schema.

**Comment by mathieutrudeau** [comment]
https://github.com/awaazo/awaazo/assets/46968018/36ac3cb0-ef24-430b-9d72-981c56969933


https://github.com/awaazo/awaazo/assets/46968018/c6ca56e7-e741-4f63-ab90-f7cf3de0bb3f

**Comment by usamasaleem1** [comment]
Usama[frontend]#3: Created frontend design for sign in and sign up pages

https://github.com/awaazo/awaazo/assets/50121574/69883326-3f9c-4289-b0ef-03cb335c8096

**Comment by jonathan-githubofficial** [comment]
initial mockups :
![login](https://github.com/awaazo/awaazo/assets/106629548/c875474b-c80a-49ac-88aa-51a636200fcb)
![sign up](https://github.com/awaazo/awaazo/assets/106629548/9177c5fd-c9bf-4194-aa22-df80b08121a0)
