### ISSUE TITLE
GET Podcast endpoint does not return ratings nor reviews

### ISSUE THREAD

**Issue by Ahed752** [awaazo/awaazo#148]
**Describe the bug**
Posting a new rating works fine, but getting the podcast by id after adding the rating still does not show the updated rate

**To Reproduce**
1. Go to 'Swagger'
2. Click on 'Post /social/rating' which will be added successfully
3. Click on 'Get /podcast/{podcastId}'
4. See error (reviews and ratings are still on 0)

**Screenshots**
![image](https://github.com/awaazo/awaazo/assets/77853391/c7f435f3-51c3-4630-9884-4f99a001222d)

The issue is in feature/podcast-reviews

**Comment by mathieutrudeau** [comment]
This issue is not found in main and will therefore be closed.
