### ISSUE TITLE
As a developer, I want to be able to retrieve podcasts based on their genres from backend endpoints, so that I can provide genre-specific content to the frontend.

### ISSUE THREAD

**Issue by Radwanbaba13** [awaazo/awaazo#151]
## Acceptance Criteria:  
- [x] Implement an endpoint for retrieving podcasts by genre.
- [x] The endpoint should accept a genre query parameter.
- [x] It should return a list of podcasts belonging to the specified genre.
- [x] Implement proper validation for the genre parameter to ensure it corresponds to valid genres.
- [x] The endpoint should handle cases where no podcasts are available for the specified genre gracefully.

## Demo Steps:  
1. Create a new branch for the feature development.
2. Implement the /api/podcasts/genres endpoint in the PodcastController.
3. Add the necessary request parameter to accept the genre query.
4. Implement a function that queries the database for podcasts belonging to the specified genre.
5. Write unit tests to ensure the functionality works as expected.
6. Test the /api/podcasts/genres endpoint using tools like Postman.
7. Request a code review from a colleague to ensure code quality and correctness.
8. Address any feedback received during the code review.
9. Merge the feature branch into the main branch.

## Potential Risks:  
- There may be performance issues with database queries if the podcast dataset is very large.
- Security vulnerabilities could arise if input validation and sanitization are not handled correctly.

## Technical Notes:  
1. Use a well-defined route structure for the new endpoint (e.g., /api/podcasts/genres?genre=your_genre).
2. Optimize database queries by using appropriate indexing for search operations.
3. Implement proper input validation and sanitation to prevent potential security issues.

**Comment by mathieutrudeau** [comment]
https://github.com/awaazo/awaazo/assets/46968018/d94d64be-53d9-4bf3-bd49-435ca8c42467
