### ISSUE TITLE
Create Episode Sections component 

### ISSUE THREAD

**Issue by jonathan-githubofficial** [awaazo/awaazo#176]
## **Description:** 
- **Brief Description:** Navigational tool for episode sections.
- **Purpose/Functionality:** Divides episodes into sections for easy navigation.
- **Related Page -frontend:** NowPlaying page.
- **Related Files/Modules -backend:** Episode segmentation module.
- **Additional Notes:** Sections should be clearly labeled for user convenience.
## Acceptance Criteria:  
- [x] Clear and labeled sections within the episode.
- [x] Seamless navigation between sections.

**Comment by jonathan-githubofficial** [comment]
mockup:
![Divisions bar](https://github.com/awaazo/awaazo/assets/106629548/3fa768d8-77db-4a6e-a84c-1db64678f63b)

**Comment by sFranchetto** [comment]
https://github.com/awaazo/awaazo/assets/31280516/ad41e5da-5625-4ae4-9896-b024dc47f29a

Commit where this was done: [link](https://github.com/awaazo/awaazo/commit/11e13d057fe9f0968a29414960ce17285408813e)
