### ISSUE TITLE
As a creator, I want to create  a podcast and manage my podcasts , so I can produce and share my content.

### ISSUE THREAD

**Issue by mubashir494** [awaazo/awaazo#18]
## Acceptance Criteria:  
- [x] Users can create a new podcast series with title, description, and cover art.
- [x] Upon creating the first podcast, the platform designates the user as a 'podcaster'.
- [x] The new series appears on the "My Podcasts" page.
- [x] Within a podcast series, creators can add, edit, or delete episodes.

## Demo Steps:  
1. Log into the platform.
2. Navigate to the "My Podcasts" page.
3. Click "Create New Podcast Series" and input necessary details (name , description , cover art , genre, real or AI-generated).
4. Observe the updated status as 'podcaster'.
5. Add or modify episodes in a podcast.

## Potential Risks:  
1. Content uploaded may not adhere to community guidelines.
2. Technical issues or downtimes that affect the user's experience.

**Comment by mubashir494** [comment]
DEMO VIDEO LINK :

[https://clipchamp.com/watch/hAq0YeOhzG2](https://clipchamp.com/watch/hAq0YeOhzG2)

**Comment by Radwanbaba13** [comment]
Radwan[frontend]: Podcast management page 
https://github.com/awaazo/awaazo/assets/68618601/497fe766-a848-431c-bae5-4a363509b0fe

**Comment by Radwanbaba13** [comment]
Radwan[frontend]: Podcast management page code overview

https://github.com/awaazo/awaazo/assets/68618601/5377afb2-b732-421a-8e41-e2c1e70ec0d3

**Comment by soni2261** [comment]
Sonia[frontend]: Podcast Creation Page Demo and Code Overview
video link:
https://clipchamp.com/watch/UJcV0RuwVde

**Comment by soni2261** [comment]
Sonia[frontend]: View Podcasts and Corresponding Episodes - Demo and Code Overview
video link:
https://clipchamp.com/watch/Un5gXpR4Pyp

**Comment by sFranchetto** [comment]
https://github.com/awaazo/awaazo/assets/31280516/d9ae3d20-44af-483f-86c9-906e1d695b2f



Commit where this was done: https://github.com/awaazo/awaazo/commit/8a95f14ee049c767cf9988d52f74ec4867537b73

**Comment by sFranchetto** [comment]
![278785350-16f99eb4-0924-4416-8727-16325f8f0482](https://github.com/awaazo/awaazo/assets/31280516/21bc9a68-16c5-447b-a282-d61b828aa8a2)
![278785361-087adffe-1cf4-4ed6-aec7-e78039dc88d2](https://github.com/awaazo/awaazo/assets/31280516/44763656-a6db-456c-ad87-de12fae7fad7)

**Comment by mathieutrudeau** [comment]
[Usability Report](https://github.com/awaazo/awaazo/files/13369385/download.pdf)
