### ISSUE TITLE
As a user, I have access to an episode's transcript, so that I can be more engaged with the episode

### ISSUE THREAD

**Issue by mathieutrudeau** [awaazo/awaazo#182]
### Acceptance Criteria:
- [ ] Add a visible "Transcript" button on the episode player page.
- [ ] Clicking the button shows the full transcript with current audio line synchronization.
- [ ] Ensure the transcript is readable and well-formatted.

### Demo Steps:
1. Open the episode player page.
2. Verify the presence of the "Transcript" button.
3. Click the button to confirm the transcript display with real-time audio line synchronization.

### Potential Risks:
- [ ] Transcript availability may vary for different episodes.
- [ ] Possible display issues with specific browsers.
- [ ] Synchronization of audio line with the transcript may have slight latency.

**Comment by mathieutrudeau** [comment]
[BACKEND](#183):

**Comment by jonathan-githubofficial** [comment]
to close this issue , this should be done : 
- [ ] backend setup a functional . issue #183 
- [ ] crud api calls are set up issue. issue #183 
- [ ] component created in the frontend for the transcript to be viewed.
