### ISSUE TITLE
As a user , I want to be able to subscribe to a specific podcast so that I can receive updates and notifications about its new episodes.

### ISSUE THREAD

**Issue by mubashir494** [awaazo/awaazo#20]
## Acceptance Criteria:  
- [x] Users can easily find and access the "Subscribe" button on a podcast's page.
- [x] Upon subscribing, users receive timely notifications (e.g., email, in-app) when a new episode of the subscribed podcast is released.
- [x] Users have the option to unsubscribe from a podcast at any time.

## Demo Steps:  
1. Navigate to a specific podcast's page.
2. Engage with the "Subscribe" button to subscribe to the podcast.
3. Receive notifications when the subscribed podcast releases new episodes.
4. Utilize the option to unsubscribe from the podcast if desired.

## Potential Risks:  
1. With platform growth, there may be challenges in delivering notifications promptly.
2. Ensuring efficient notification delivery on mobile platforms.

**Comment by mubashir494** [comment]
DEMO PART 1 (Backend) : https://clipchamp.com/watch/6g2NeiidN9m
DEMO PART 2 (Backend) : https://clipchamp.com/watch/HDrv7jJUr9E

**Comment by jonathan-githubofficial** [comment]
Subscribe button under the My Podcasts container should be added for this issue to be close , ensuring full integration .
duplicate issue #113 , will be removed.

**Comment by Radwanbaba13** [comment]
@soni2261 
You can add the subscribe button here:
/Components/Explore/PodcastOverview.tsx

This component will be rendered in "/pages/Explore/[id].tsx", but you shouldn't have to worry about this file for now

**Comment by Ahed752** [comment]
https://github.com/awaazo/awaazo/assets/77853391/839f2b7d-60fa-4318-87d2-480b1579e834

**Comment by Ahed752** [comment]
https://github.com/awaazo/awaazo/assets/77853391/7a54add6-9ce1-4697-bccd-4d203694d8f7

Subscribe/Unsubscribe button + subscriptions list are completed

**Comment by sFranchetto** [comment]
https://github.com/awaazo/awaazo/assets/31280516/67330a1c-4a2c-4507-b8cc-f3e88b348819

Commit where this was done: [link](https://github.com/awaazo/awaazo/commit/11e13d057fe9f0968a29414960ce17285408813e)
