### ISSUE TITLE
Notifications API needs some fixes

### ISSUE THREAD

**Issue by Ahed752** [awaazo/awaazo#210]
**Describe the bug**
Media (image URL) is identical for all new episodes
Link does not redirect users to Podcast (it redirects to invalid page) 

**To Reproduce**
1. Go to any page with the NavBar
2. Click on Bell Icon
3. See Notifications from other podcasts

**Screenshots**
![image](https://github.com/awaazo/awaazo/assets/77853391/7d02bf9a-a106-4d3f-a822-d4e34b72a5bd)

**Comment by mubashir494** [comment]
- Media is fixed in the new PR
- For link you have to manually redirect the user to podcast page (Eg : Link :some Id ,Redirect : http://some-frontent-url/{Link} )

**Comment by Ahed752** [comment]
Closed in PR #196
