### ISSUE TITLE
Podcasts not showing on home page

### ISSUE THREAD

**Issue by sFranchetto** [awaazo/awaazo#217]
**Describe the bug**
When logged in as a User, no podcast is shown on the homepage, nor if I visit a user's profile that has podcasts uploaded it will not show me their podcasts & episodes

**Screenshots**
![image](https://github.com/awaazo/awaazo/assets/31280516/8956a9ae-c5d6-4118-8a13-52dba97c428d)

![image](https://github.com/awaazo/awaazo/assets/31280516/444bd280-5448-4ac1-a507-efc3c1bf39c2)

![image](https://github.com/awaazo/awaazo/assets/31280516/f618f2e7-3056-4925-a518-b5dafbd6db48)

**Additional context**
We suspect is has to do with have more than 3 users registered at once.

**Comment by mathieutrudeau** [comment]
https://github.com/awaazo/awaazo/assets/46968018/d35c5401-5aa5-43ae-bd09-73e54e4f2c0d
