### ISSUE TITLE
As a listener, I want to access AI-generated summaries of an episode, to determine its relevance to my interests.

### ISSUE THREAD

**Issue by sFranchetto** [awaazo/awaazo#25]
**Acceptance Criteria:**  
1. An option to view or listen to AI-generated episode summaries is prominently available.
2. Summaries accurately capture the episode's key points and main topics.
3. Users can access these summaries both as a preview before starting and as a recap after listening.

**Demo Steps:**  
1. Navigate to a desired podcast episode.
2. Engage with the option to view or listen to the AI-generated summary.
3. Assess the episode's relevance based on the provided summary.
4. Choose to proceed with the full episode or explore other content.

**Potential Risks:**  
- AI-generated summaries might miss nuanced details or misrepresent episode content.
- High computational resources might be needed to create summaries for numerous episodes.
- Possible privacy concerns when using AI for content summarization.

**Comment by mathieutrudeau** [comment]
![Capture](https://github.com/awaazo/awaazo/assets/46968018/498454e9-a511-4614-b194-1aa97c95b267)
![Capture1](https://github.com/awaazo/awaazo/assets/46968018/f704390d-f98a-446c-93c5-d66188a0bac2)

**Comment by mathieutrudeau** [comment]
A default prompt was added to the chatbot to generate an AI summary of the episode.

**Comment by mathieutrudeau** [comment]
# Risks 
- The AI summary is generated using the vectorized db for the episode. Therefore, the context in which it generates the summary is tied to the episode's content.
- The computations are done using Groq's API and uses 200 tokens at most, while our current maximum is over 10000 tokens/minute.
- The AI summary does not make use of any information other than the episode transcript and public information on which the model was trained.
