### ISSUE TITLE
As a user, I want to create playlists of my favorite podcast episodes, allowing me to listen to a tailored sequence of episodes.

### ISSUE THREAD

**Issue by mubashir494** [awaazo/awaazo#26]
**Acceptance Criteria:**  
1. Users can provide a name and description when creating a playlist.
2. Users can easily search for and add podcast episodes to their playlists.
3. An "Add to playlist" button is prominently displayed for each episode.
4. Upon clicking "Add to playlist", users can see and select from their existing playlists.
5. Successfully added episodes appear in the chosen playlist.

**Demo Steps:**  
1. Navigate to the dashboard and click the "Create Playlist" button.
2. Enter the desired playlist name and description.
3. Browse available podcast episodes.
4. For a desired episode, click the "Add to playlist" button.
5. From the pop-up, select an existing playlist to add the episode to.

**Potential Risks:**  
- Removing a podcast episode from the platform could disrupt user-created playlists.
- An unintuitive interface might hinder the playlist creation process.

**Comment by jonathan-githubofficial** [comment]
no frontend for this story was made

**Comment by mathieutrudeau** [comment]
Refactored the playlist endpoints [this issue](#223 )
