### ISSUE TITLE
Create an endpoint to provide access to episode transcripts.

### ISSUE THREAD

**Issue by jonathan-githubofficial** [awaazo/awaazo#277]
## Acceptance Criteria:  
- [x] Endpoint successfully retrieves the transcript for a given episode ID.
- [x] The response includes the complete transcript text, along with associated metadata.
- [x] The endpoint should handle requests and deliver responses efficiently to minimize latency.

## Demo Steps:  
1. Verify that the endpoint is accessible and responds to requests for episode transcripts.
2. Test with a valid episode ID to ensure the correct transcript is retrieved.
3. Check the response efficiency and accuracy of the transcript data.

## Potential Risks:  
- High demand for transcripts might result in server overload or latency issues.
- Inaccurate or incomplete transcripts could lead to user dissatisfaction.

## Technical Notes:  
- Consider implementing caching for frequently requested transcripts to improve response times.
- Implement error handling and logging to troubleshoot potential issues effectively.

**Comment by jonathan-githubofficial** [comment]
this issue is a prerequisite for #168

**Comment by jonathan-githubofficial** [comment]
is it possible to move to using WhisperX?
https://github.com/m-bain/whisperX

**Comment by mathieutrudeau** [comment]
Will add more endpoints, in order to reduce the amount of data (transcript lines) being retrieved.
