### ISSUE TITLE
Create a Component for PodCue Annotations and make it visible in NowPlaying Page

### ISSUE THREAD

**Issue by jonathan-githubofficial** [awaazo/awaazo#279]
**Description:**
Develop a frontend component to display PodCue annotations (links, info, sponsorships, media links) at specified timestamps in the NowPlaying page of the app. This component should allow users to interact with these annotations during podcast playback.

**Functionality:**
- Display annotations at the correct timestamps during playback.
- Interactive elements for users to engage with the content (e.g., clicking a link, watch a  YouTube video picture-in-picture ).
- Integration with the current playback interface.

**Acceptance Criteria:**
- [x] Annotations appear synchronously with the podcast timestamp.
- [x] Each annotation type (link, info, sponsorship, media-link) is distinctly represented.
- [x] User interactions with annotations are smooth and intuitive.
- [x] The component fits seamlessly with the existing NowPlaying page design.

**Comment by jonathan-githubofficial** [comment]
<img width="881" alt="Screenshot 2024-01-06 071854" src="https://github.com/awaazo/awaazo/assets/106629548/7e20458f-ddbc-4bdb-8e10-754ed423cb64">

**Comment by Ahed752** [comment]
This issue is closed in PR #292
