### ISSUE TITLE
Remove the "Required" field on a Playlist cover art

### ISSUE THREAD

**Issue by sFranchetto** [awaazo/awaazo#290]
**Describe the bug**
Playlist expects a cover art image to be received when creating a playlist, but has one generated at time of creation.

**To Reproduce**
1. Log in
2. Create a playlist
3. Error should be shown

**Screenshots**
![image](https://github.com/awaazo/awaazo/assets/31280516/72cdffa1-bada-4867-b4d3-67113d77f5a9)

**Additional context**
![image](https://github.com/awaazo/awaazo/assets/31280516/fc59bce8-9a24-4dbb-9007-409e73d40cee)

**Comment by jonathan-githubofficial** [comment]
the fix is just to make the "CoverArt" attribute optional
