### ISSUE TITLE
Podcasts disappear after writing a Review

### ISSUE THREAD

**Issue by sFranchetto** [awaazo/awaazo#291]
**Describe the bug**
When a user writes a Review on a Podcast, that Podcast disappears from the website but is still present on the user that wrote the review.

**To Reproduce**
1. User 1 creates a podcast and makes it visible
2. User 2 writes a review on that podcast
3. User 2 goes on homepage, still sees podcast there along with review
4. User 1 goes on homepage, no podcasts shows up
5. User 1 goes on /CreatorHub/MyPodcasts and no podcasts show up
6. User 1 goes to create a podcast with the same name as step 1, they are met with: A podcast with that name already exists

**Screenshots**

User 1
![image](https://github.com/awaazo/awaazo/assets/31280516/016c8a42-bfcf-41d1-9554-be2b95825616)
![image](https://github.com/awaazo/awaazo/assets/31280516/67ed2bd7-2189-4c00-a485-ae113bad76bc)
![image](https://github.com/awaazo/awaazo/assets/31280516/65db9e07-8f9f-4903-b306-d23eb0544611)

User 2
![image](https://github.com/awaazo/awaazo/assets/31280516/a5e2eb27-4d3c-4676-a02a-1fa0ae8bfe5d)
![image](https://github.com/awaazo/awaazo/assets/31280516/9fcba1c9-64e1-498b-9fc0-b49c89b0debc)

Console
![image](https://github.com/awaazo/awaazo/assets/31280516/739cfdfd-48e2-42b2-8bb7-2a2a407236f0)
![image](https://github.com/awaazo/awaazo/assets/31280516/9ab81ffc-026a-4a9a-860d-a1579522ebbd)

**Comment by mathieutrudeau** [comment]
![Capture](https://github.com/awaazo/awaazo/assets/46968018/94411662-6ae9-4e0b-b681-f0d26c10b112)
The issue is that when retrieving a podcast, it also retrieves all ratings/reviews for that podcast. Somehow the user that owns the rating/review is set to null, causing the exception to be thrown.

**Comment by mathieutrudeau** [comment]
The problem originates from the LINQ query, which does not return the user for the ratings. Adding the following include .ThenInclude(r => r.User) fixed the issue. I will make sure that this fix is applied to all queries that return ratings.
