### ISSUE TITLE
Not being able to delete a podcast if a review is present on the Podcast.

### ISSUE THREAD

**Issue by sFranchetto** [awaazo/awaazo#296]
**Describe the bug**
If a Review is present on a podcast, the system throws an error if the user tries to delete it [podcast].

**To Reproduce**
1. Create podcast
2. Leave a Review
3. Delete podcast
4. Podcast doesn't delete

**Screenshots**
![image](https://github.com/awaazo/awaazo/assets/31280516/188e627b-32ae-4f87-ba0f-abb31ca366c2)

![image](https://github.com/awaazo/awaazo/assets/31280516/e1af01f4-095f-47e7-a28d-28b8abd252ac)

**Comment by mathieutrudeau** [comment]
Message = "The DELETE statement conflicted with the REFERENCE constraint \"FK_PodcastRatings_Podcasts_PodcastId\". The conflict occurred in database \"soen490\", table \"dbo.PodcastRatings\", column 'PodcastId'."
