### ISSUE TITLE
As a podcaster, I want to see my podcast watch metrics, so I can see how well my content is performing. 

### ISSUE THREAD

**Issue by Radwanbaba13** [awaazo/awaazo#299]
## Acceptance Criteria:
- [ ] The podcast dashboard (CreatorHub/Mypodcasts page) includes a section for watch metrics.
- [ ] Metrics such as total listens, likes, and average listen duration are displayed.
- [ ] The metrics are presented in an easily understandable format, such as charts or graphs.
- [ ] The watch metrics are filterable by date range for better analysis.
- [ ] Podcasters can view metrics for individual episodes as well as an overall summary.

## Demo Steps:
1. Log in to the podcast dashboard.
2. Navigate to the "Metrics" or "Analytics" section.
3. Observe the total listens, likes, and average listen duration.

## Potential Risks:
- [ ] Inaccurate metrics due to technical issues or data processing errors.
- [ ] Delay in metric updates, affecting the real-time monitoring of podcast performance.
- [ ] Difficulty in interpreting or understanding the presented metrics.
- [ ] Security concerns related to the storage and handling of podcast watch metrics data.

**Comment by soni2261** [comment]
Due to huge amount of debugging (migrations errors), this issue has been delayed. Working on it ASAP.
