### ISSUE TITLE
As a frontend developer, I want an endpoint that returns a list of recently uploaded episodes and podcasts with public access.

### ISSUE THREAD

**Issue by Radwanbaba13** [awaazo/awaazo#302]
## Acceptance Criteria:
- [x] An endpoint is created to retrieve a list of recently uploaded episodes and podcasts with public access.
- [x] The endpoint does not require user authentication, allowing access to non-signed-in users.
- [x] The response includes relevant details such as episode/podcast title, description, upload date, etc.
- [x] The list is sorted in descending order based on the upload date.
- [x] The endpoint handles pagination to efficiently manage the data retrieval.

## Demo Steps:
1. Access the endpoint without being signed in.
2. Verify that the response includes a list of recently uploaded episodes and podcasts.
3. Confirm that the list is sorted in descending order based on the upload date.
4. Test the pagination functionality by fetching additional sets of recently uploaded content.

## Potential Risks:
- [x] Increased server load due to potential high demand for recently uploaded content.
- [x] Privacy concerns if sensitive information is unintentionally exposed in the response.
- [x] Inefficient pagination implementation leading to slower response times.

## Technical Notes:
- [x] Implement rate limiting to prevent abuse of the endpoint.
- [x] Ensure that only publicly accessible content is included in the response.

**Comment by BigSaladMan** [comment]
In terms of risks, Pagination helps mitigate most of them. Server load is lessened since SQL queries are most succinct which leads to faster response times.
In terms of privacy, the special response object only returns necessary things, thus privacy is not a concern
