### ISSUE TITLE
As a frontend developer, I want an endpoint that will store the playlist queue  (list of episodes) the user last had in the player.

### ISSUE THREAD

**Issue by Radwanbaba13** [awaazo/awaazo#309]
## Acceptance Criteria:
- [ ] An endpoint is created to store the playlist queue for the user in the player.
- [ ] The playlist queue data is securely stored and associated with the user.
- [ ] Users can retrieve their last playlist queue by making a request to the endpoint.
- [ ] The endpoint handles potential edge cases, such as empty or invalid playlist queue data.

## Demo Steps:
1. Make a request to the endpoint to store a playlist queue for a specific user.
2. Verify that the playlist queue data is successfully stored.
3. Retrieve the last playlist queue for the same user and confirm it matches the stored data.
4. Test the endpoint with various scenarios, including empty or malformed playlist queue data.

## Potential Risks:
- [ ] Security vulnerabilities if the endpoint is not properly secured against unauthorized access.
- [ ] Data integrity issues if the playlist queue is not accurately stored or retrieved.
- [ ] Increased server load if there is a high demand for frequent playlist queue updates.
- [ ] Inefficient data storage leading to slower response times.

## Technical Notes:
- [ ] Implement proper authentication mechanisms to secure the endpoint.
- [ ] Consider data encryption for playlist queue storage to enhance security.

**Comment by BigSaladMan** [comment]
Playlist is still broken in main as of now, pushing this to next release

**Comment by BigSaladMan** [comment]
This is a cut feature, asked the frontend dev (radwan), and we will not be implementing this
