### ISSUE TITLE
Edit Profile system failing

### ISSUE THREAD

**Issue by sFranchetto** [awaazo/awaazo#314]
**Describe the bug**
Edit Profile system causing a crash, system not interactable.

**To Reproduce**
1. Log in
2. Go to My Account
3. Click 'Edit Profile' button

**Screenshots**
When 'Edit Profile' button clicked, user is met with this error: 
![image](https://github.com/awaazo/awaazo/assets/31280516/c05b449b-6b98-4e59-8946-45b34acdc22a)
![image](https://github.com/awaazo/awaazo/assets/31280516/80e5a1ec-26f9-414b-a1c8-231d11681d7f)

**Additional context**
No I will not activate Windows...

**Comment by BigSaladMan** [comment]
Looking at the screenshot you provided, it looks like the issue is with the website loading the avatar of the user you are trying to edit. I tried this on my side and I cant repro this (I am on the current version of main at this point).

**Comment by BigSaladMan** [comment]
I looked into the backend code a little more, seems like we dont have any validation on what type of file actually comes in. Could be that you updated it to a file type that the frontend didnt like, causing it to crash
