### ISSUE TITLE
As a developer, I want a CI/CD pipeline to deploy merged code to production instantly, ensuring users get the latest updates promptly.

### ISSUE THREAD

**Issue by mubashir494** [awaazo/awaazo#32]
**Acceptance Criteria:**  
1. The CI/CD pipeline detects when new code is merged into the main branch.
2. The pipeline initiates an automatic deployment immediately after a merge event.
3. The deployment process is seamless and requires no manual intervention.
4. The production environment reflects the latest merged changes.
5. Deployment logs or notifications are available, ensuring transparency and traceability.

**Demo Steps:**  
1. A developer completes a feature or fix and submits a pull request.
2. After code review and approval, the code is merged into the main branch.
3. The CI/CD pipeline detects the merge and begins the deployment process.
4. The code is successfully deployed to the production environment.
5. Developers and stakeholders verify that the new code is live and functional.

**Potential Risks:**  
1. Automated deployment through the CI/CD pipeline might push untested or unstable code to production.
2. Continuous deployment could introduce unforeseen conflicts or issues.
3. The pipeline must ensure no disruption to ongoing services or user experiences during deployment.

**Comment by mathieutrudeau** [comment]
https://github.com/awaazo/awaazo/assets/46968018/61602eee-b127-4e7a-a210-49ac32d02cac

**Comment by mathieutrudeau** [comment]
The CI/CD pipeline will be changed so that the production version of the app is hosted on Concordia servers.

**Comment by jonathan-githubofficial** [comment]
this issue is used as a pre requirement to #254
