### ISSUE TITLE
Create Podcast Image Upload and 'Done' button not fully visible in CreatorHub

### ISSUE THREAD

**Issue by soni2261** [awaazo/awaazo#324]
**Describe the bug**
Uploading an Image and 'Done' button not fully visible in CreatorHub

**To Reproduce**
1. CreatorHub/CreatePodcast
2. Add new podcast
3. Upload a podcast image
4. Image is not fully visible and 'done' button is hidden

**Screenshots**
<img width="935" alt="image" src="https://github.com/awaazo/awaazo/assets/61927635/499bf3c0-b239-4df3-87da-9effd2f3e3fb">

**Comment by jonathan-githubofficial** [comment]
this issue is already fixed
