### ISSUE TITLE
User cannot logout

### ISSUE THREAD

**Issue by BigSaladMan** [awaazo/awaazo#337]
**Describe the bug**
The log out button currently does not work. If you try to log out, it fails with this message in the console
![image](https://github.com/awaazo/awaazo/assets/78050750/2a85eb5e-de33-4a80-9fe2-f2901360107e)

This command does work in the backend, so the problem is that the request fails to make it to the backend

**To Reproduce**
1. Create a user
2. Sign in
3. Click on the logout button on the top right
4. Page will refresh without actually logging out

**Screenshots**
see above

**Additional context**
As a workaround, you can just log off by directly calling the backend /auth/logout endpoint, where the user will actually be logged out

**Comment by mathieutrudeau** [comment]
Is that bug occurring on main?

**Comment by BigSaladMan** [comment]
Further testing reveals that this only happens in firefox browsers. Chrome is safe from this bug. Currently happening in master
