### ISSUE TITLE
As a podcaster, I want to access analytics about my podcasts, so that I can gain a better understanding of my audience

### ISSUE THREAD

**Issue by mathieutrudeau** [awaazo/awaazo#338]
## Acceptance Criteria:
- [x] The tool accurately captures and displays podcast watch time.
- [x] The tool provides insights into the average age of the podcast audience.
- [x] The tool includes a feature to analyze the most popular episodes based on user engagement.
- [x] Podcast owners can access a user-friendly dashboard summarizing key analytics.

## Demo Steps:
1. Navigate to the "Analytics" section on the creator hub.
2. Observe the real-time podcast watch time graph.
3. Access the demographic analytics page to view the average age of the audience.
4. Click on the "Top Episodes" tab to see analytics for the most popular episodes.
5. Check the dashboard for a summarized overview of key podcast analytics.

## Potential Risks:
- [x] Inaccurate data collection leading to misleading analytics.
- [x] Privacy concerns regarding the collection and storage of demographic information.
- [x] Technical issues causing delays or disruptions in the real-time analytics feature.
- [x] Potential user dissatisfaction if the tool's interface is not intuitive or user-friendly.

[This issue covers the creation of the backend endpoints](https://github.com/awaazo/awaazo/issues/390)

**Comment by Radwanbaba13** [comment]
Risk Mitigations:
Enhanced data validation protocols to ensure accurate analytics.
Implemented user-friendly interface updates based on feedback.
