### ISSUE TITLE
As a user, I want to access insights about my listening habits, so that I can better understand my usage patterns

### ISSUE THREAD

**Issue by mathieutrudeau** [awaazo/awaazo#339]
## Acceptance Criteria:
- [x] Users can view their total podcast watch time.
- [x] Users can see a breakdown of their podcast listening habits by genre.
- [x] The tool provides personalized recommendations based on the user's listening history.
- [x] Users can easily navigate and filter their listening history to view specific episodes or time periods.
- [x] The tool offers insights into the most listened-to podcasts and episodes.
- [x] The user can customize the time range for which they want to view their listening habits.
- [x] The tool is accessible and user-friendly for individuals with different levels of technical expertise.

## Demo Steps:
1. Navigate to the "Podcast Insights" section of the tool.
2. Observe the total podcast watch time displayed on the dashboard.
3. Explore the genre breakdown to understand preferences.
4. Receive and review personalized podcast recommendations.
5. Use the filtering options to view listening history for a specific time range.
6. Check the most listened-to podcasts and episodes.
7. Customize the time range and observe the real-time updates.
8. Ensure the tool is easy to navigate for users with varying technical skills.

## Potential Risks:
- [x] The tool may not accurately capture watch time if there are issues with data synchronization.
- [x] Personalized recommendations might not be precise if the user's listening history is limited.
- [x] Users with a large listening history may experience performance issues.
- [x] Privacy concerns related to the collection and usage of podcast listening data.
- [x] Difficulty in interpreting or understanding the insights provided by the tool.
- [x] The tool may not appeal to users with diverse podcast genre preferences.
- [x] Possible dissatisfaction if recommendations do not align with user expectations.

**Comment by Radwanbaba13** [comment]
Risk Mitigations:
Improved data synchronization processes to enhance accuracy in capturing watch time.
Enhanced recommendation algorithms to provide more precise suggestions, considering diverse user listening histories.
