### ISSUE TITLE
As a developer, I want select features to be accessible even for users without a session, so that we can provide a more inclusive and user-friendly experience for all visitors.

### ISSUE THREAD

**Issue by Radwanbaba13** [awaazo/awaazo#370]
## Acceptance Criteria:  

All of the following endpoints do not require authorization:
- [x] /annotation/{id}/getAnnotation
- [x] /playlist/{id}/getUserPlaylists
- [x] /playlist/all
- [x] /playlist/search
- [x] /playlist/{id}
- [x] /playlist/{id}/getCoverArt
- [x] /podcast/userPodcasts
- [x] /podcast/all
- [x] /podcast/search
- [x] /podcast/{id}
- [x] /podcast/{id}/getCoverArt
- [x] /podcast/byTags
- [x] /podcast/getRecentPodcasts
- [x] /podcast/episode/{id}
- [x] /podcast/{id}/{id}/getAudio
- [x] /podcast/{id}/{id}/getThumbnail
- [x] /podcast/{id}/adjacentEpisode
- [x] /podcast/episode/search
- [x] /podcast/{id}/getTranscript
- [x] /podcast/{id}/getTranscriptText
- [x] /podcast/getRecentEpisodes
- [x] /profile/search
- [x] /profile/{id}/get
- [x] /profile/{id}/avatar
- [x] /section/{id}/get

## Demo Steps:  
1. Access the platform as a user without a session.
2. Navigate to the features identified as accessible without authentication.
3. Interact with these features to ensure full functionality.
4. Attempt to access features not on the accessible list to verify restriction.

## Potential Risks:  
- [x] Unauthenticated access may increase the risk of spam or abuse.
- [x] Difficulty in tracking user behavior and preferences without a session.
- [x] Potential for confusion if the difference between authenticated and unauthenticated access is not clear.
- [x] Increased load on the system due to unauthenticated use.

## Technical Notes:  
- [x] Ensure backend APIs can differentiate between authenticated and unauthenticated requests.
- [x] Regularly review and update the list of features accessible without authentication.

**Comment by mubashir494** [comment]
addressed in pr #406
