### ISSUE TITLE
As a developer, I want to episodes to be uploaded and assigned an ID immediately, with their upload status tracked, so that I can allow for additional content editing even before the transcript is fully processed.

### ISSUE THREAD

**Issue by Radwanbaba13** [awaazo/awaazo#372]
## Acceptance Criteria:  
- [ ] Upon upload request, each episode is immediately assigned a unique ID.
- [ ] The system accurately tracks and updates the upload status of each episode (Uploaded, Error, InProgress).
- [ ] Episodes are set to private until their transcript is generated.
- [ ] Functionality to add sections and annotations to the episode before the transcript is complete.
- [ ] The episode remains inaccessible to other users until the transcript is ready and the episode is made public.
- [ ] Proper error handling and feedback mechanisms for any issues during the upload or processing stages.

## Demo Steps:  
1. Initiate the upload process for an episode.
2. Verify that an ID is assigned immediately to the episode.
3. Check the status updates of the episode (Uploaded, Error, InProgress).
4. Add sections and annotations to the episode during the InProgress state.
5. Confirm that the episode is private until the transcript is generated.
6. Once the transcript is ready, validate that the episode becomes public.

## Potential Risks:  
- [ ] Handling simultaneous uploads and status updates without performance degradation.
- [ ] Ensuring data consistency during the upload and editing phases.
- [ ] Securing the episode content when it is in a private state.
- [ ] Efficiently managing the transition from private to public state post transcript generation.

## Technical Notes:  
- [ ] Implement a robust state management system to track episode status.
- [ ] Use database transactions to ensure atomicity of operations during upload and editing.
- [ ] Implement role-based access control to manage visibility and edit permissions.
- [ ] Optimize database queries and server responses for handling large files and concurrent requests.

**Comment by mathieutrudeau** [comment]
The issues (slow upload speed or no upload) are due to the dns provider.  Any request sent from the frontend over 100MB will freeze and/or get denied with the following response.

```<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->```

**Comment by mathieutrudeau** [comment]
Also keep the backend does not wait for the transcript to be ready before sending back the podcast episode id.

**Comment by mathieutrudeau** [comment]
The issue was fixed by having the request broken down into smaller chunks.
