### ISSUE TITLE
As a Developer  , I want to have an endpoint to generate transcripts for podcast episodes, So that I can manually trigger transcription for episodes where automatic transcription has not occurred or failed.

### ISSUE THREAD

**Issue by jonathan-githubofficial** [awaazo/awaazo#375]
## Acceptance Criteria:  
- [x] Endpoint `/podcast/{episodeId}/generateTranscript` is implemented.
- [x] The endpoint checks if a transcript already exists for the given episode and it's not empty or corrupt.
- [x] If a transcript exists, return a message indicating that it already exists.
- [x] If no transcript exists, trigger the transcription process.
- [x] The transcription process involves running `app.add_routes([web.get('/{podcast_id}/{episode_file_name}/create_transcript', handle_transcription_request)])` from the Python container microservice.
- [x] Show progress of the transcription process.

## Demo Steps:  
1. Access the endpoint with an episode ID.
2. Verify that it checks for an existing transcript.
3. If no transcript exists, observe the process of transcription initiation.
4. Check for the progress updates on the transcription process.
5. Verify the endpoint's response once the transcript is available.

## Potential Risks:  
- [x] Endpoint misuse or overuse, leading to system overload.
- [x] Transcription errors or delays in processing.
- [x] Potential failure in checking the existence of a transcript.

## Technical Notes:  
- [x] Ensure secure handling and storage of podcast episodes and transcripts.
- [x] Implement appropriate authentication and authorization checks for the endpoint.
- [x] Consider rate limiting to prevent abuse of the transcription service.
- [x] Integrate logging and monitoring for troubleshooting and performance analysis.

**Comment by mathieutrudeau** [comment]
# Risks
- Any error thrown by the transcription service are logged into a status file, which can be accessed by the ASP.net server.
- If a transcript already exists for the same episode, the transcription service will not generate a new transcription.
