### ISSUE TITLE
As a user, I want the ability to use Awaazo as a progressive web app

### ISSUE THREAD

**Issue by usamasaleem1** [awaazo/awaazo#386]
Description:

As a user of Awaazo, I want to be able to add the website to my home screen and use it as a progressive web app (PWA) so that I can easily access it in full-screen mode and enjoy a seamless browsing experience similar to a native mobile app.

Acceptance Criteria:

- Implement functionality for users to add Awaazo to their home screen on both Android and iOS devices.
- Ensure that when launched from the home screen, Awaazo opens in full-screen mode without any browser UI elements.
- Enable offline access to previously loaded content when the user is not connected to the internet.
- Implement responsive design to provide a consistent user experience across various screen sizes and orientations.
- Test the PWA functionality on different browsers and devices to ensure compatibility and performance.
  
Demo Steps:

1. Demonstrate the process of adding Awaazo to the home screen on Android and iOS devices.
2. Show how launching Awaazo from the home screen opens it in full-screen mode.
3. Test offline access by disconnecting from the internet and accessing previously loaded content.
4. Showcase the responsive design by using Awaazo on different devices and screen sizes.

Potential Risks:

- Compatibility issues with certain browsers or operating system versions.
- Ensuring that the PWA provides a smooth and intuitive user experience comparable to a native app.
- Addressing any security concerns related to offline access and data storage on the user's device.

Technical Notes:

- Utilize service workers to enable offline access and caching of resources.
- Implement a responsive design using CSS media queries to adapt to various screen sizes.
- Use the Web App Manifest to configure how Awaazo appears when added to the home screen.
- Perform thorough testing and optimization to ensure fast load times and smooth performance, especially on mobile devices.

**Comment by BigSaladMan** [comment]
Cut feature
