### ISSUE TITLE
As a developer, I want to easily use our CI, so that I can code faster

### ISSUE THREAD

**Issue by BigSaladMan** [awaazo/awaazo#404]
## Acceptance Criteria:  
- [x] Making migrations be built when the CI is ran, letting us not have to fix them manually
- [x] Having the CI be more reliable for causes of failures, since right now they almost always fail due to CI
- [x] Removing bloat from our commits by removing migrations altogether from pushes

## Potential Risks:  
- less control over what migrations the database builds from could lead to some issues
- Potential to be more headache inducing than the issues currently caused by migrations

## Technical Notes:  
- I will be trying to add migrations as a build step during our CI, making it so that these are done independently
- I will need to update the gitignore as well, to prevent us from unnecessarily uploading migrations from now on

**Comment by mathieutrudeau** [comment]
The migrations are deleted and automatically updated prior to building the backend image. This ensure that the testing suite will always run on a new migration.
