### ISSUE TITLE
As a user, I want to view and edit the episode transcript, so that I can ensure an understanding of the podcast content

### ISSUE THREAD

**Issue by soni2261** [awaazo/awaazo#427]
# Episode Transcript Editing Implementation

## Acceptance Criteria
- [x] Transcript accessible in Nowplaying Page
- [x] Transcript can be edited in a form in Creator Hub

## Demo Steps

1. Show transcript displayed in Nowplaying Page
2. Show edit transcript button displayed in Creator Hub
3. Show (open/close) form when editing transcript
4. Show submitting edited transcript

## Potential Risks

- [x] Wrong text being written down
- [x] Performance issues on lower-end devices.
- [x] Compatibility issues with certain browsers.
- [x] Potential layout shifts during toggle on different screen sizes.

**Comment by mathieutrudeau** [comment]
Note: When moving the audio to a different position (Say skipping forward). The transcription will only show when a new line starts.
