### ISSUE TITLE
As a user, I want to share my top podcast episodes or playlists on social media platforms such as X,  Facebook, and Instagram to recommend content to my network.

### ISSUE THREAD

**Issue by Radwanbaba13** [awaazo/awaazo#47]
**Acceptance Criteria:**  
1. Users can readily find and use the social sharing features for episodes and playlists.
2. Shared content on social media platforms appears correctly with an attractive podcast image and a brief description.
3. User privacy is upheld, ensuring no unintentional sharing of sensitive information.

**Demo:**  
1. User chooses a podcast episode or playlist to share.
2. User clicks the "Share" button or icon.
3. A social media sharing menu appears.
4. User picks a platform and navigates to its sharing interface.
5. User can personalize their post message before sharing.

**Potential Risks:**  
1. Technical obstacles in achieving smooth integration with various social media.
2. Ensuring user privacy and data security during social media sharing.

**Comment by Ahed752** [comment]
https://github.com/awaazo/awaazo/assets/77853391/392ffb4b-2120-46c5-ae26-dac327eab054

**Comment by Ahed752** [comment]
closed in PR #292
