### ISSUE TITLE
As a user, I want notifications for new episodes from my followed or recommended podcasts to stay updated on fresh content.

### ISSUE THREAD

**Issue by Radwanbaba13** [awaazo/awaazo#51]
**Acceptance Criteria:**  
1. Users can conveniently access and modify podcast notification settings.
2. Notifications are sent only for selected or followed podcasts.
3. New episode notifications are timely.
4. Users can customize or turn off notifications as desired.

**Demo:**  
1. User navigates to notification settings in their profile.
2. Options are presented to toggle notifications for specific podcasts.
3. User specifies preferred notification channel (in-app, email, push).
4. Upon a new episode's release, a notification is sent to the user.

**Potential Risks:**  
1. Delays or inaccuracies in delivering notifications.
2. Risk of overwhelming users with excessive notifications.

**Comment by usamasaleem1** [comment]
Usama[frontend]#1: Created hovering modal frontend design for notifications panel

https://github.com/awaazo/awaazo/assets/50121574/5f2f16f8-4440-4225-a80e-a53dac5b8fcc
