### ISSUE TITLE
As a user, I want to rate podcasts with star ratings and reviews to assist others in discovering quality content.

### ISSUE THREAD

**Issue by Radwanbaba13** [awaazo/awaazo#52]
**Acceptance Criteria:**  

1.  Overall podcast rating is an accurate average of user ratings.
2.  Users can submit text reviews alongside their ratings.
3. All ratings and reviews for the podcast are displayed on its info page.
4. Mechanisms are in place to detect and handle fraudulent or abusive ratings and reviews. Users can report inappropriate content.

**Demo Steps:**  
1. During a podcast episode playback, users are presented with a rating widget.
5. Users can assign a rating to the podcast using a bird rating system similar to 1-5 star system (happy, smiling, mutual, dissatisfied, sad Awaazo bird ).
6. An option is available for users to write a review.
7. Upon submission, ratings and reviews are publicly visible.

**Potential Risks:**  
1. Inconsistent access to the rating and review feature across various devices or browsers.
2. Challenges in ensuring the average rating accuracy due to potential data inconsistencies.
3. The presence of fraudulent reviews may threaten the platform's trustworthiness.

**Comment by mathieutrudeau** [comment]
Backend endpoints have been added.

**Comment by Ahed752** [comment]
https://github.com/awaazo/awaazo/assets/77853391/0f0e1189-2542-4c49-9f8b-f7b8e9402d3a

**Comment by sFranchetto** [comment]
https://github.com/awaazo/awaazo/assets/31280516/ce3b2e0a-2a21-4d28-88f8-9e7084b2cb45




Commit where this was done: [Commit](https://github.com/awaazo/awaazo/commit/f46abc0693b8be6a4acd9cfa35a323b0e85d78ad)
