### ISSUE TITLE
As a user, I want to edit my profile info to update my personal details so that I can have a personalized experience on the platform.

### ISSUE THREAD

**Issue by sFranchetto** [awaazo/awaazo#7]
## Acceptance Criteria:  
- [x] Only logged-in users can access the "Edit info" button on the Profile page.
- [x] User's updated info is validated, consistent, and stored in the database.
- [x] New info is displayed on the user's profile publicly.

## Demo Steps:  
1. User clicks the avatar icon and selects "My profile."
2. On the profile page, user clicks the "Edit info" button.
3. User is taken to a form with fields like Country, Profile picture, Date of birth, About me, and podcast preferences.
4. After filling out the form, the user clicks "Save changes."
5. If there's an error in input, feedback is provided on the incorrect field.

## Potential Risks:  
1. Ensuring user privacy and data security.
2. Making the profile management process user-friendly.

**Comment by mathieutrudeau** [comment]
https://github.com/awaazo/awaazo/assets/46968018/0e8939ae-4b7c-4316-a558-34f7a75dd6dd

**Comment by usamasaleem1** [comment]
Usama[frontend]#2: Frontend Design


https://github.com/awaazo/awaazo/assets/50121574/bb12099d-ff05-4319-8947-339a05f86443

**Comment by sFranchetto** [comment]
https://github.com/awaazo/awaazo/assets/31280516/45b15e66-d9c6-4428-9f88-e8729e066e92


Commit where this was done: https://github.com/awaazo/awaazo/commit/ced44fc7519db6b3a132a047b10a95c2a42adf5b

**Comment by Radwanbaba13** [comment]
Radwan[frontend]: User Setup page Demo

https://github.com/awaazo/awaazo/assets/68618601/42d1b0f6-41c8-40da-b68c-6b3ac8ca64f8

**Comment by sFranchetto** [comment]
![278785383-b2b778a9-1222-4c73-af6a-133b76cfa300](https://github.com/awaazo/awaazo/assets/31280516/80d7f932-441d-4501-9c62-1478df1d46d3)
![278785393-327cb7f2-7715-4435-aaec-e879ebdbf5a0](https://github.com/awaazo/awaazo/assets/31280516/f44e4452-c3cd-454c-a670-057a025711f9)

**Comment by mathieutrudeau** [comment]
[Usability Report](https://github.com/awaazo/awaazo/files/13369379/download.pdf)
